name: Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Zip file path'
        required: true
        type: choice
        options:
          - info/export
          - warning/export
          - debug/export

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "This job runs on the main branch when triggered."
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
