name: Manual Dispatch

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "This job runs on the main branch when manually triggered."
        echo ${{ github.ref }}
        echo ${{ github.head_ref }}
        echo ${{ github.Base_ref }}
