name: Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "This job runs on the main branch when triggered."
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
