name: Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Zip file path'
        required: true
        default: ''
        type: choice
        options:
          - 'Select an option'
          - info/export
          - warning/export
          - debug/export
      
      Folder:
        description: 'Environment based policy folder'
        required: true
        type: choice
        options:
          - ./Production/Policies/
          - ./Dev_QA/Policies/
      
      Files:
        description: 'Policy file names'
        required: true

jobs:
  example-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.logLevel != 'Select an option' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "This job runs on the main branch when triggered."
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo ${{ github.run_attempt }}

    - name: Input logs
      run: |
        echo ${{ github.event.inputs.logLevel }}
        echo ${{ github.event.inputs.Folder }}
        echo ${{ github.event.inputs.Files }}

    - name: Check Import Solution Result
      # if: steps.import-solution.conclusion == 'failure'
      run: |
        echo "Import solution step failed. Rerunning the job..."
        gh run rerun ${{ github.run_id }} --failed
