name: Test SQL auto workflow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  Test-SQL-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tag the Latest Commit After Successful Deployment
        if: success()  # Only tag if deployment was successful
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git tag -f last-deploy  # Force update the tag
          git push origin last-deploy --force
