name: Test SQL auto workflow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  Test-SQL-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tag the Latest Commit After Successful Deployment
        if: success()  # Only tag if deployment was successful
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if the tag exists
          if git rev-parse --quiet --verify "refs/tags/last-deploy"; then
            echo "Tag 'last-deploy' already exists. Updating..."
            git tag -f last-deploy  # Force update the tag
          else
            echo "Tag 'last-deploy' does not exist. Creating new tag..."
            git tag last-deploy  # Create a new tag
          fi
          
          git push origin last-deploy --force
