name: Test SQL workflow

on:
  workflow_dispatch:
    inputs:
      Folder_name:
        description: 'Select a SQL folder name'
        required: true
        type: choice
        options:
          - 'Select a Folder'
          - \Database\DB\dbo\Tables\
          - \Database\DB\custom_scripts\
      Dev_SQL_file_name:
        description: 'Enter Dev SQL file name'
        required: true

jobs:
  Test-SQL-Workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.Folder_name != 'Select a SQL folder name' && github.event.inputs.Dev_SQL_file_name != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate SQL File Name
        run: |
          if [[ "${{ github.event.inputs.Dev_SQL_file_name }}" != *.sql ]]; then
            echo "Error: The file name must have a .sql extension."
            exit 1
          fi
          
      - name: Set SQL Script Path
        id: set_sql_path
        run:  |
          SQL_SCRIPT_PATH="${{ vars.SCRIPTPATH }}${{ github.event.inputs.Folder_name }}${{ github.event.inputs.Dev_SQL_file_name }}"
          echo "SQL_SCRIPT_PATH=$SQL_SCRIPT_PATH"  >> $GITHUB_ENV

      - name: Test ENV
        run: |
          echo "ENV value: $SQL_SCRIPT_PATH"
